// Bilingual content for Huasheng Metal corporate site
// All copy is data-driven so language can be toggled without re-rendering structure.

window.HS_CONTENT = {
  cn: {
    brand: {
      short: "华盛金属",
      full: "广州华盛金属材料有限公司",
      legal: "© 2025 广州华盛金属材料有限公司 版权所有",
      tagline: "30 年金属精工，匠造城市公共器物",
    },
    nav: {
      home: "首页",
      about: "关于我们",
      capabilities: "核心能力",
      cases: "项目案例",
      quality: "质量与认证",
      blog: "企业动态",
      contact: "联系我们",
      cta: "获取报价",
    },
    home: {
      eyebrow: "始于 1989 · 国内第一批现代化候车亭制造商",
      heroTitle: "为城市，造一件\n经得起时间的金属作品",
      heroSub: "从北京奥运到香港高铁，从卡塔尔到尼泊尔——华盛 30 年专注公共候车亭、广告灯箱、不锈钢工程与精密金属 OEM。",
      heroCta1: "查看项目案例",
      heroCta2: "了解生产能力",
      stats: [
        { num: "30+", label: "年金属加工经验" },
        { num: "120,000", label: "平方米生产基地" },
        { num: "297", label: "台精密加工设备" },
        { num: "40+", label: "海外项目落地国家" },
      ],
      intro: {
        eyebrow: "关于华盛",
        title: "一家把候车亭做了三十年的工厂",
        body: "1989 年，华盛在广州起步。1993 年成立金属材料公司，为广州打造了城市第一代现代化候车亭。三十余年过去，我们仍把同一件事做到极致：把一块冷轧钢、一根铝合金型材，变成一件可以在城市街角立三十年的金属作品。",
      },
      capabilities: {
        eyebrow: "我们能做什么",
        title: "从一张图纸到一个城市部件",
        items: [
          {
            tag: "01",
            title: "公共候车亭与广告灯箱",
            body: "国内第一批现代化候车亭制造商，多项设计专利。覆盖全国大中城市，落地北京奥运、香港高铁、海外政府项目。",
          },
          {
            tag: "02",
            title: "钢结构装修装饰工程",
            body: "不锈钢幕墙、钢结构装饰、定制金属构件。承接大型公共空间与商业项目的金属表达。",
          },
          {
            tag: "03",
            title: "精密金属 OEM / ODM",
            body: "为 IKEA 等国际品牌提供厨房手推车、橱柜、置物架、卫浴金属配件等 OEM 代工。",
          },
          {
            tag: "04",
            title: "一站式设计制造交付",
            body: "从设计、研发、生产、表面处理、装配、装柜、到海外吊装指导，全流程在自有工厂内完成。",
          },
        ],
      },
      featured: {
        eyebrow: "项目案例",
        title: "三十年，建过的金属",
        viewAll: "查看全部项目",
      },
      clients: {
        eyebrow: "合作客户",
        title: "国内外政府与品牌客户",
        list: ["IKEA 宜家", "香港地铁 MTR", "北京奥运组委会", "卡塔尔政府", "新西兰邮政", "韩国市政", "阿曼项目部", "罗马尼亚交通"],
      },
      resources: {
        eyebrow: "官方资料入口",
        title: "统一实体资料与外部目录链接",
        lede: "把旧官网、B2B 目录和新的 canonical 官网连接起来。外部平台后台获得登录权限后，website 字段统一更新为 https://hua-sheng.org。",
        note: "这些入口用于客户核验企业主体、产品目录和历史公开资料；正式询价仍建议回到 hua-sheng.org 或直接联系华盛团队。",
        items: [
          {
            tag: "Legacy",
            title: "旧官网",
            body: "原有企业官网入口，后续应在页头、页脚、联系页和站点地图中显著指向新官网。",
            href: "https://www.huasheng-metal.com/",
            display: "huasheng-metal.com",
          },
          {
            tag: "Alibaba",
            title: "Alibaba 供应商展厅",
            body: "广州华盛金属材料在 Alibaba 的外贸供应商展厅，用于承接海外买家询盘。",
            href: "https://gzhsgm.en.alibaba.com/",
            display: "gzhsgm.en.alibaba.com",
          },
          {
            tag: "Made-in-China",
            title: "Made-in-China 展厅",
            body: "Made-in-China 平台供应商主页，覆盖候车亭、灯箱和金属公共设施等产品目录。",
            href: "https://gz-huasheng.en.made-in-china.com/",
            display: "gz-huasheng.en.made-in-china.com",
          },
          {
            tag: "GoldSupplier",
            title: "GoldSupplier 企业资料",
            body: "面向 bus stop、light box、retail kiosk 等采购场景的外部企业资料页。",
            href: "https://gzhsgm.goldsupplier.com/",
            display: "gzhsgm.goldsupplier.com",
          },
          {
            tag: "Source",
            title: "网站源代码仓库",
            body: "旧版公开网站实现仓库，保留为可追溯的站点资料来源。",
            href: "https://github.com/ZaynJarvis/huasheng",
            display: "GitHub source",
          },
        ],
      },
      footerCta: {
        title: "有项目要做？",
        sub: "无论你是城市规划方、广告运营商、海外政府采购，还是寻找长期 OEM 合作伙伴——我们都欢迎一次具体的对话。",
        btn: "发起咨询",
      },
    },
    about: {
      hero: {
        eyebrow: "关于我们",
        title: "始于 1989 的华盛企业集团",
        sub: "华盛从广州出发，围绕公共交通设施、城市家具、户外亭体与金属制品，把设计、制造、安装和项目交付连接成完整能力。",
      },
      story: {
        title: "从工贸起步，到多元产业",
        paragraphs: [
          "1989 年，广州市华盛工贸有限公司在广州创立。“华盛”二字由华国锋同志亲笔题写，这一历史印记也成为企业长期发展的精神锚点。",
          "三十余年来，华盛逐步形成先进工业制造与安装、产业园开发与管理、商业地产开发与管理、新能源开发与管理协同发展的业务框架。",
          "在先进工业制造与安装领域，华盛持续投入广州花都银亿斯先进智造产业园，建设现代化厂房、员工宿舍、高效生产线与智能制造设施，形成公共设施和金属制品的综合制造基地。",
          "华盛长期拓展国内与国际市场，业务已覆盖全球 100+ 城市和地区，主要产品包括公共交通候车亭、城市家具、户外亭体与厨房、金属家居用品及定制金属构件。",
          "依托项目经验、制造设备和质量管理体系，华盛与 White Horse Outdoor、IKEA、Belson Outdoors、Valeo、BYD Backyard、Ladenbau Schmidt 等客户和伙伴建立长期合作。",
          "从广州第一代现代化候车亭，到北京 LED 公交线路牌、上海智能候车亭、深圳前海与福田智慧候车亭，再到沙特、卡塔尔等海外交通设施项目，华盛始终把城市公共空间里的小设施做成可持续交付的工程产品。",
        ],
      },
      milestones: {
        title: "企业里程碑",
        items: [
          { year: "1989", title: "华盛创立", body: "广州市华盛工贸有限公司成立，“华盛”名称由华国锋同志亲笔题写。" },
          { year: "1993", title: "候车亭制造起步", body: "华盛金属材料体系逐步成形，为广州打造第一代现代化公交候车亭。" },
          { year: "2001", title: "国际客户合作", body: "与 IKEA 等国际客户建立长期制造合作，金属制品进入全球供应链。" },
          { year: "2008", title: "国家级项目经验", body: "承接北京奥运相关公共设施项目，进一步积累大型城市项目交付能力。" },
          { year: "2014", title: "海外交通设施", body: "卡塔尔、沙特、阿曼、尼泊尔等海外项目持续落地，形成跨境制造与安装经验。" },
          { year: "2020", title: "智慧公交系统", body: "北京 LED 公交线路牌、深圳智慧候车亭、西安 LCD 智能候车亭等项目推动产品智能化。" },
          { year: "2025", title: "先进智造产业园", body: "广州花都银亿斯先进智造产业园持续完善，承载制造、配套与产业管理能力升级。" },
        ],
      },
      group: {
        title: "核心经营主体",
        sub: "新版 Catalog 中披露的核心公司主体，覆盖工贸、金属材料、交通设施安装、产业投资与物业管理。",
        items: [
          "广州市华盛工贸有限公司",
          "广州华盛金属材料有限公司",
          "广州银亿交通设施安装工程有限公司",
          "广州银亿斯投资发展有限公司",
          "广州银亿恒物业管理有限公司",
        ],
      },
      business: {
        eyebrow: "四大业务板块",
        title: "制造、园区、商业与新能源协同发展",
        sub: "华盛不是单一产品工厂，而是围绕城市公共设施和先进制造形成多板块协同的产业体系。",
        items: [
          { tag: "01", title: "先进工业制造与安装", body: "公共交通候车亭、城市家具、户外亭体、金属家居与定制金属构件的设计、制造、包装、安装支持。" },
          { tag: "02", title: "产业园开发与管理", body: "广州花都银亿斯先进智造产业园承载现代厂房、员工宿舍、生产线和配套管理能力。" },
          { tag: "03", title: "商业地产开发与管理", body: "通过产业空间和商业空间运营，为制造、仓储、展示与服务配套提供长期支撑。" },
          { tag: "04", title: "新能源开发与管理", body: "围绕新型能源设备、网络终端柜、氢能充装相关设施和通信基站散热系统拓展新业务。" },
        ],
      },
      clients: {
        eyebrow: "客户与合作伙伴",
        title: "从国内城市项目到全球品牌供应链",
        sub: "华盛的合作横跨公共交通、户外家具、家居零售、汽车零部件、商超陈列和新能源设施。",
        items: [
          { tag: "GLOBAL", title: "White Horse Outdoor / Belson Outdoors", body: "长期参与海外户外公共设施和城市家具供应，支持不同城市环境下的结构、包装与交付。" },
          { tag: "OEM", title: "IKEA 瑞典宜家", body: "以稳定焊接、表面处理和质量控制能力，支持功能型家居与金属收纳产品制造。" },
          { tag: "AUTO", title: "Valeo", body: "面向工业客户提供金属制造和项目协作能力，强调交付稳定性和过程质量。" },
          { tag: "OUTDOOR", title: "BYD Backyard", body: "围绕户外厨房、凉亭等产品，把金属加工能力延伸到现代庭院生活场景。" },
          { tag: "RETAIL", title: "Ladenbau Schmidt", body: "为瑞士商超和专业零售空间提供不锈钢产品与制造支持，服务 Coop、Migros 等本地零售体系。" },
          { tag: "CITY", title: "国内城市公共设施客户", body: "服务北京、上海、广州、深圳、无锡、西安、重庆等城市的公交、导视、信息屏和公共空间项目。" },
        ],
      },
      projects: {
        eyebrow: "项目案例更新",
        title: "新版 Catalog 中呈现的代表项目",
        sub: "以下项目按地域和产品形态做摘要展示，完整案例仍可在项目页继续扩展。",
        items: [
          { tag: "北京", title: "智能 LED 公交线路指示牌", body: "高亮 LED 屏、远程更新、节能组件和全天候结构，让线路信息在高峰与夜间都清晰可见。" },
          { tag: "上海", title: "智能候车亭项目", body: "高强度钢结构、耐候材料、模块化安装、曲面排水顶棚和集成照明，提升城市候车体验。" },
          { tag: "广州", title: "花城书屋、木棉亭与南沙项目", body: "以城市文化为设计线索，结合公共服务、信息服务、照明、Wi-Fi、共享充电和自助售卖功能。" },
          { tag: "深圳", title: "前海与福田智慧候车亭", body: "集成导视屏、触控查询、夜间照明和开放式结构，让候车亭成为城市数字入口。" },
          { tag: "无锡 / 西安 / 重庆", title: "运河城市与 LCD 智能候车亭", body: "将不锈钢结构、镜面细节、USB 充电、智能售卖和高分辨率信息屏结合到日常通勤场景。" },
          { tag: "中东", title: "利雅得、达曼、麦加与卡塔尔项目", body: "面向高温、强日照和本地文化语境，提供遮阳、通风、预制构件、海外物流和现场安装支持。" },
        ],
      },
      technology: {
        eyebrow: "技术与制造能力",
        title: "从金属加工到智能显示系统",
        sub: "新版 Catalog 进一步强调华盛在智慧城市设施和工厂装备上的自有能力。",
        items: [
          { tag: "DISPLAY", title: "自研 LED/LCD 显示系统", body: "应用于公交候车亭广告屏、导视屏和城市信息亭，支持实时信息、动态导航和触控交互。" },
          { tag: "COATING", title: "自动化粉末喷涂生产线", body: "覆盖自动喷涂、人工补喷、最终装配和质量检查，服务户外耐候金属产品。" },
          { tag: "SMARTTECH", title: "激光切割与焊接机器人", body: "高功率激光切割机、焊接机器人、CNC 剪板机和铝型材切割设备支撑精密制造。" },
          { tag: "ENERGY", title: "高效散热系统合作产品", body: "面向通信基站冷却改造，利用自然冷源与智能控制算法，实现散热系统与原空调联动。" },
        ],
      },
      mission: {
        eyebrow: "企业使命",
        title: "质量是我们的未来",
        body: "产品质量是华盛的未来。我们希望以稳定制造、工程交付和长期合作，为社会发展、工业进步与产业文化贡献力量。",
      },
      values: {
        eyebrow: "使命与价值观",
        title: "Insight · Precision · Advancement · Partnership",
        items: [
          { tag: "Insight", title: "洞察", body: "理解街道家具、公共设施和城市使用场景，帮助客户把产品做得更贴合真实环境。" },
          { tag: "Precision", title: "精准", body: "用工程思维、设计协作、设备能力和质量流程，把项目更快、更稳、更安全地推进。" },
          { tag: "Advancement", title: "进取", body: "三十余年制造经验沉淀为持续改进能力，在关键节点提供可落地的创新方案。" },
          { tag: "Partnership", title: "伙伴关系", body: "把客户目标视为共同任务，与客户、设计方、安装方和供应链一起完成交付。" },
        ],
      },
    },
    cap: {
      hero: {
        eyebrow: "核心能力",
        title: "一座 5 万平米的金属工厂，能做的事",
        sub: "从原材料到成品装柜，全流程在自有厂房内闭环完成。",
      },
      plantStats: [
        { num: "120,000", unit: "m²", label: "厂房总面积" },
        { num: "5", unit: "大", label: "加工车间" },
        { num: "297", unit: "台", label: "精密加工设备" },
        { num: "4", unit: "条", label: "生产线" },
        { num: "600+", unit: "人", label: "一线员工" },
        { num: "40%", unit: "", label: "产能余量" },
      ],
      workshops: {
        title: "五大加工车间",
        sub: "厂房按工序划分为办公楼与五个独立车间，物料按节拍流转。",
        items: [
          { tag: "01", title: "五金加工区", body: "激光切割、CNC 冲剪、折弯、开槽、水切割。冷轧钢、不锈钢、铝合金、镀锌板的成型基础。" },
          { tag: "02", title: "铆焊加工区", body: "机器人自动焊接 + 人工精焊。承接结构件与外观件的焊接工艺。" },
          { tag: "03", title: "表面处理区", body: "数字化自动喷涂生产线，含前处理、电泳、粉末喷涂、烘烤等完整工序。" },
          { tag: "04", title: "清洁装配区", body: "在洁净环境下完成最终装配、电气与配件集成、出厂前的质量检查。" },
          { tag: "05", title: "出货装柜区", body: "图腾式装柜方案，最大化集装箱利用率，配套海外吊装指导与现场服务。" },
        ],
      },
      equipment: {
        title: "重点设备",
        sub: "297 台设备中，覆盖从切割、成型到表面的所有关键工序。",
        items: [
          "400W 激光切割机",
          "机器人自动焊接工作站",
          "数字化自动喷涂线",
          "CNC 折弯机 / 剪板机",
          "CNC 冲床",
          "弯管机 / 开槽机",
          "水切割机",
          "电泳前处理生产线",
        ],
      },
      process: {
        title: "标准生产工艺流程",
        steps: [
          { n: "01", t: "设计 / 工艺评审", d: "工程团队评估图纸、出工艺方案" },
          { n: "02", t: "材料 IQC 进料检验", d: "钢材、铝材、配件入库前抽检" },
          { n: "03", t: "下料 / 切割 / 成型", d: "激光切割、冲剪、折弯、弯管" },
          { n: "04", t: "焊接 / 铆接", d: "机器人焊接 + 人工精焊" },
          { n: "05", t: "表面处理", d: "前处理、电泳、喷涂、烘烤" },
          { n: "06", t: "装配 / 调试", d: "电气、配件、灯箱集成与点亮测试" },
          { n: "07", t: "FQC 终检", d: "外观、结构、电气全项检验" },
          { n: "08", t: "包装 / 装柜 / 发货", d: "图腾装柜方案，海外吊装指导" },
        ],
      },
    },
    cases: {
      hero: {
        eyebrow: "项目案例",
        title: "三十年里，我们造过的金属",
        sub: "从一座北京奥运的不锈钢候车亭，到一座尼泊尔山城的政府岗亭。",
      },
      filters: ["全部", "国内候车亭", "海外项目", "钢结构工程", "OEM 代工"],
      featured: {
        title: "Beijing 北京奥运不锈钢候车亭",
        loc: "中国 · 北京",
        amount: "工程量 ¥12,723,000",
        year: "2008",
        body: "为北京奥运场馆周边设计制作的不锈钢候车亭项目，是华盛承接的标志性国家级工程。",
      },
      items: [
        { cat: "国内候车亭", title: "广州第一代现代候车亭", loc: "中国 · 广州", year: "1993", amount: "—", body: "为广州城市打造的第一代现代化公交候车亭，开启国内现代候车亭制造序章。" },
        { cat: "国内候车亭", title: "上海世博会候车亭", loc: "中国 · 上海", year: "2010", amount: "¥25,645,000", body: "上海世博会及主城区公交候车亭项目，结合城市景观、广告灯箱与无障碍候车体验。" },
        { cat: "国内候车亭", title: "杭州公共自行车亭", loc: "中国 · 杭州", year: "2012", amount: "¥7,963,000", body: "杭州公共自行车系统配套候车与停放亭，集成信息显示与照明。" },
        { cat: "国内候车亭", title: "鄂尔多斯候车亭", loc: "中国 · 鄂尔多斯", year: "2015", amount: "¥3,000,000", body: "适应寒冷干旱气候的候车亭批量项目，含防风与采暖结构。" },
        { cat: "海外项目", title: "卡塔尔多哈候车亭", loc: "卡塔尔 · 多哈", year: "2010s", amount: "—", body: "适应中东高温环境的候车亭项目，含遮阳、降温与广告灯箱集成。" },
        { cat: "海外项目", title: "香港 MTR 售票咨询柜台", loc: "中国 · 香港", year: "2016", amount: "—", body: "为香港地铁高铁站台设计制作的不锈钢售票与咨询柜台。" },
        { cat: "海外项目", title: "尼泊尔政府项目", loc: "尼泊尔", year: "2017", amount: "—", body: "尼泊尔政府公共设施项目，含候车亭、岗亭与信息牌。" },
        { cat: "海外项目", title: "新西兰邮政亭", loc: "新西兰", year: "2018", amount: "—", body: "为新西兰邮政设计制作的金属邮政服务亭，适应海岛潮湿气候。" },
        { cat: "海外项目", title: "阿曼公共项目", loc: "阿曼", year: "2018", amount: "—", body: "中东沙漠环境下的公共候车与遮阳结构。" },
        { cat: "海外项目", title: "韩国铝合金候车亭", loc: "韩国", year: "2019", amount: "—", body: "全铝合金结构的现代候车亭，针对韩国市政标准化设计。" },
        { cat: "海外项目", title: "罗马尼亚铝合金路牌", loc: "罗马尼亚", year: "2017", amount: "—", body: "为罗马尼亚交通系统提供的铝合金导向路牌项目。" },
        { cat: "海外项目", title: "利雅得候车亭", loc: "沙特阿拉伯 · 利雅得", year: "2018", amount: "—", body: "面向中东高温环境的金属候车亭项目，集成遮阳顶棚、玻璃围护与独立导视柱。" },
        { cat: "海外项目", title: "土耳其与土库曼项目", loc: "土耳其 · 土库曼", year: "2019", amount: "—", body: "中亚与西亚的市政公共设施项目。" },
        { cat: "钢结构工程", title: "钢结构装修装饰工程", loc: "中国 · 多地", year: "—", amount: "—", body: "不锈钢幕墙、装饰构件、大型公共空间的金属表达。" },
        { cat: "OEM 代工", title: "IKEA 厨房手推车", loc: "—", year: "2001 至今", amount: "—", body: "为 IKEA 长期供货的金属厨房手推车系列。" },
        { cat: "OEM 代工", title: "IKEA 橱柜与厨房家具金属件", loc: "—", year: "2001 至今", amount: "—", body: "橱柜、厨房家具的金属配件 OEM 代工。" },
        { cat: "OEM 代工", title: "毛巾架与卫浴搁架", loc: "—", year: "2001 至今", amount: "—", body: "卫浴金属配件批量代工。" },
        { cat: "OEM 代工", title: "置物架与金属配件", loc: "—", year: "2001 至今", amount: "—", body: "家居置物架与金属配件批量代工。" },
      ],
    },
    quality: {
      hero: {
        eyebrow: "质量与认证",
        title: "把可信，做成可以验证的流程",
        sub: "ISO 9001 认证，多项设计专利，DMAIC 质量管理体系。",
      },
      policy: {
        title: "质量方针",
        sub: "作为 ISO 9001 认证体系的一部分，质量方针指导我们的一切动作。我们对质量的承诺有两根支柱。",
        pillars: [
          { tag: "支柱一", t: "守住承诺", d: "按时交付符合约定要求的产品，满足客户的需求与期望。" },
          { tag: "支柱二", t: "持续改进", d: "持续监控并改进业务、产品与服务、组织与员工绩效。" },
        ],
      },
      dmaic: {
        title: "DMAIC 质量管控流程",
        sub: "客户体验 → 定义 → 测量 → 分析 → 改进 → 控制，覆盖从来料到出货的每一道工序。",
        steps: [
          { n: "D", t: "定义 Define", d: "明确产品规格、客户期望与验收标准。" },
          { n: "M", t: "测量 Measure", d: "IQC 进料、首件检验、过程检验全程数据采集。" },
          { n: "A", t: "分析 Analyze", d: "针对不合格品分析根因，CAR 纠正措施单。" },
          { n: "I", t: "改进 Improve", d: "工艺改进与返工流程，避免同类问题再次发生。" },
          { n: "C", t: "控制 Control", d: "FQC 终检、IPQC 过程巡检、入库前最终验证。" },
        ],
      },
      certs: {
        title: "资质与专利",
        items: [
          { t: "ISO 9001 质量管理体系", d: "覆盖设计、生产、装配、出货全流程。" },
          { t: "候车亭外观设计专利", d: "国内最早一批候车亭外观设计专利持有企业。" },
          { t: "候车亭结构实用新型专利", d: "多项实用新型专利覆盖结构、灯箱、连接件等。" },
          { t: "IKEA 合格供应商资格", d: "通过 IKEA 全球供应链合规审核，长期供货资格。" },
        ],
      },
    },
    contact: {
      hero: {
        eyebrow: "联系我们",
        title: "把项目说给我们听",
        sub: "无论城市规划、广告运营、海外政府采购、或长期 OEM 合作——我们都欢迎一次具体的对话。",
      },
      info: {
        addr: { t: "厂房地址", v: "中国 · 广东省 · 广州市" },
        phone: { t: "联系电话 / WhatsApp", v: "+65 8309-9012" },
        email: { t: "邮箱", v: "hi@hua-sheng.org" },
        contact: { t: "对接负责人", v: "Zayn Jarvis 刘经理" },
        hours: { t: "工作时间", v: "每天 10:00-22:00 (GMT+8)" },
      },
      form: {
        title: "项目咨询",
        sub: "填写下面的简短表单，我们会在 1 个工作日内回复。",
        fields: {
          name: "您的称呼",
          company: "公司 / 机构",
          email: "邮箱 *",
          phone: "电话 / WhatsApp",
          country: "国家 / 地区",
          type: "项目类型",
          types: ["候车亭项目", "广告灯箱", "钢结构工程", "OEM 代工", "其他"],
          message: "请简单描述您的需求（数量、时间、预算等）",
          submit: "发送咨询",
        },
      },
    },
  },

  en: {
    brand: {
      short: "HUASHENG",
      full: "Guangzhou HuaSheng Metal Materials Co., Ltd.",
      legal: "© 2025 Guangzhou HuaSheng Metal Materials Co., Ltd. All Rights Reserved.",
      tagline: "30 Years of Metal Craft for Public Cityscapes",
    },
    nav: {
      home: "Home",
      about: "About",
      capabilities: "Capabilities",
      cases: "Projects",
      quality: "Quality",
      blog: "Blog",
      contact: "Contact",
      cta: "Get a Quote",
    },
    home: {
      eyebrow: "Since 1989 · China's first generation of modern bus shelter makers",
      heroTitle: "Built for the street.\nMade to last decades.",
      heroSub: "From the Beijing Olympics to Hong Kong MTR, from Qatar to Nepal — HuaSheng has spent 30 years designing and manufacturing bus shelters, advertising light boxes, stainless steel structures and precision metal OEM.",
      heroCta1: "Browse projects",
      heroCta2: "Our capabilities",
      stats: [
        { num: "30+", label: "Years in metal fabrication" },
        { num: "120,000", label: "m² production base" },
        { num: "297", label: "Precision machines" },
        { num: "40+", label: "Countries delivered to" },
      ],
      intro: {
        eyebrow: "About HuaSheng",
        title: "A factory that has been making bus shelters for three decades",
        body: "HuaSheng started in Guangzhou in 1989. In 1993 the metal-materials subsidiary was formed and built the city's first generation of modern bus shelters. Three decades on, we are still doing the same thing — turning cold-rolled steel and aluminium extrusions into objects that stand on a street corner for thirty years.",
      },
      capabilities: {
        eyebrow: "What we do",
        title: "From a drawing to a piece of the city",
        items: [
          { tag: "01", title: "Bus shelters & light boxes", body: "Among the first modern bus shelter makers in China. Multiple design patents. Delivered to the Beijing Olympics, Hong Kong MTR and dozens of overseas governments." },
          { tag: "02", title: "Steel structure & decoration", body: "Stainless steel facades, decorative structures, custom architectural metalwork for public and commercial spaces." },
          { tag: "03", title: "Precision metal OEM / ODM", body: "Long-term OEM partner of IKEA: kitchen trolleys, cabinets, shelving, bathroom metal parts." },
          { tag: "04", title: "End-to-end delivery", body: "Design, R&D, fabrication, finishing, assembly, container loading, overseas installation guidance — all in-house." },
        ],
      },
      featured: {
        eyebrow: "Selected work",
        title: "Three decades of metal, built",
        viewAll: "View all projects",
      },
      clients: {
        eyebrow: "Clients & partners",
        title: "Governments and brands at home and abroad",
        list: ["IKEA", "Hong Kong MTR", "Beijing Olympics Committee", "Government of Qatar", "New Zealand Post", "Korean Municipalities", "Sultanate of Oman", "Romanian Transport"],
      },
      resources: {
        eyebrow: "Official profile links",
        title: "Entity links across controlled directories",
        lede: "Connecting the legacy website, B2B directory profiles, and the new canonical website. When account access is available, each external profile should set its website field to https://hua-sheng.org.",
        note: "These links help buyers verify the company entity, product directories, and historical public information. Formal enquiries should still return to hua-sheng.org or contact the Huasheng team directly.",
        items: [
          {
            tag: "Legacy",
            title: "Legacy official website",
            body: "The controlled legacy company website. It should point visitors to the new canonical domain from key site areas.",
            href: "https://www.huasheng-metal.com/",
            display: "huasheng-metal.com",
          },
          {
            tag: "Alibaba",
            title: "Alibaba supplier showroom",
            body: "Huasheng's Alibaba supplier showroom for overseas buyer discovery and trade enquiries.",
            href: "https://gzhsgm.en.alibaba.com/",
            display: "gzhsgm.en.alibaba.com",
          },
          {
            tag: "Made-in-China",
            title: "Made-in-China showroom",
            body: "The Made-in-China supplier profile covering shelters, light boxes, and metal public facilities.",
            href: "https://gz-huasheng.en.made-in-china.com/",
            display: "gz-huasheng.en.made-in-china.com",
          },
          {
            tag: "GoldSupplier",
            title: "GoldSupplier profile",
            body: "External company profile for bus stop, light box, and retail kiosk sourcing.",
            href: "https://gzhsgm.goldsupplier.com/",
            display: "gzhsgm.goldsupplier.com",
          },
          {
            tag: "Source",
            title: "Website source repository",
            body: "The previous public implementation repository, retained as a traceable website source.",
            href: "https://github.com/ZaynJarvis/huasheng",
            display: "GitHub source",
          },
        ],
      },
      footerCta: {
        title: "Got a project in mind?",
        sub: "City planner, advertising operator, overseas government buyer, or long-term OEM partner — we welcome a concrete conversation.",
        btn: "Start an enquiry",
      },
    },
    about: {
      hero: {
        eyebrow: "About us",
        title: "Founded in 1989, built for urban public facilities and advanced manufacturing",
        sub: "From Guangzhou, HuaSheng connects design, metal manufacturing, installation support and project delivery for public transport facilities, urban furniture, outdoor pavilions and custom metal products.",
      },
      story: {
        title: "From industry and trade to a diversified industrial ecosystem",
        paragraphs: [
          "HuaSheng was founded in Guangzhou in 1989. The name HuaSheng was personally inscribed by Hua Guofeng, a historical mark that became part of the company's long-term identity.",
          "Over more than three decades, HuaSheng has developed a coordinated business framework covering advanced industrial manufacturing and installation, industrial park development and management, commercial real estate development and management, and new energy development and management.",
          "In advanced manufacturing, HuaSheng continues to invest in the Yinyisi Advanced Intelligent Manufacturing Industrial Park in Huadu, Guangzhou, combining modern workshops, staff dormitories, efficient production lines and smart manufacturing facilities.",
          "HuaSheng serves more than 100 cities and regions worldwide. Its products include public transport shelters, urban furniture, outdoor pavilions and kitchens, metal household goods and custom metal components.",
          "With project experience, manufacturing equipment and quality systems, HuaSheng has built long-term relationships with White Horse Outdoor, IKEA, Belson Outdoors, Valeo, BYD Backyard, Ladenbau Schmidt and other clients and partners.",
          "From Guangzhou's first generation of modern bus shelters to Beijing LED bus route signs, Shanghai smart shelters, Shenzhen Qianhai and Futian smart shelters, and public transport projects in Saudi Arabia and Qatar, HuaSheng turns small urban facilities into deliverable engineering products.",
        ],
      },
      milestones: {
        title: "Milestones",
        items: [
          { year: "1989", title: "Founded", body: "Guangzhou HuaSheng Industry & Trade Co., Ltd. founded; the HuaSheng name was inscribed by Hua Guofeng." },
          { year: "1993", title: "Shelter manufacturing begins", body: "The metal materials business takes shape and builds Guangzhou's first generation of modern bus shelters." },
          { year: "2001", title: "International customers", body: "Long-term manufacturing cooperation with IKEA and other overseas customers brings HuaSheng into global supply chains." },
          { year: "2008", title: "National project experience", body: "Public facility work around Beijing Olympic venues strengthens large urban project delivery capability." },
          { year: "2014", title: "Overseas transport projects", body: "Projects in Qatar, Saudi Arabia, Oman, Nepal and more build cross-border manufacturing and installation experience." },
          { year: "2020", title: "Smart transit systems", body: "Beijing LED route signs, Shenzhen smart shelters and Xi'an LCD shelters push products toward intelligent operation." },
          { year: "2025", title: "Advanced manufacturing park", body: "The Yinyisi Advanced Intelligent Manufacturing Industrial Park in Huadu continues to upgrade production and management capacity." },
        ],
      },
      group: {
        title: "Core operating entities",
        sub: "Core entities highlighted in the latest catalog, covering industry and trade, metal materials, traffic facility installation, industrial investment and property management.",
        items: [
          "Guangzhou HuaSheng Industry & Trade Co., Ltd.",
          "Guangzhou HuaSheng Metal Materials Co., Ltd.",
          "Guangzhou Yinyi Transportation Facilities Installation Engineering Co., Ltd.",
          "Guangzhou Yinyisi Investment Development Co., Ltd.",
          "Guangzhou Yinyiheng Property Management Co., Ltd.",
        ],
      },
      business: {
        eyebrow: "Four business pillars",
        title: "Manufacturing, industrial park, property and new energy",
        sub: "HuaSheng is not a single-product workshop; it is a coordinated industrial system built around urban public facilities and advanced manufacturing.",
        items: [
          { tag: "01", title: "Advanced manufacturing & installation", body: "Design, fabrication, packing and installation support for transport shelters, urban furniture, outdoor pavilions, metal household products and custom components." },
          { tag: "02", title: "Industrial park development", body: "The Yinyisi Advanced Intelligent Manufacturing Industrial Park in Huadu combines modern workshops, dormitories, production lines and management systems." },
          { tag: "03", title: "Commercial real estate management", body: "Industrial and commercial spaces support manufacturing, storage, showroom and service functions over the long term." },
          { tag: "04", title: "New energy development", body: "New business around energy infrastructure, network terminal cabinets, hydrogen-related facilities and cooling systems for communication base stations." },
        ],
      },
      clients: {
        eyebrow: "Clients & partners",
        title: "From city projects to global brand supply chains",
        sub: "HuaSheng works across public transport, outdoor facilities, home retail, automotive supply, retail fit-out and new energy equipment.",
        items: [
          { tag: "GLOBAL", title: "White Horse Outdoor / Belson Outdoors", body: "Long-term participation in overseas outdoor public facilities and urban furniture supply, with structure, packing and delivery support." },
          { tag: "OEM", title: "IKEA Sweden", body: "Stable welding, surface treatment and quality-control capability for functional home and metal storage products." },
          { tag: "AUTO", title: "Valeo", body: "Metal manufacturing and project collaboration for industrial customers, with emphasis on delivery stability and process quality." },
          { tag: "OUTDOOR", title: "BYD Backyard", body: "Outdoor kitchens and gazebos that extend HuaSheng's metal fabrication capability into modern backyard living." },
          { tag: "RETAIL", title: "Ladenbau Schmidt", body: "Stainless steel products and manufacturing support for Swiss retail spaces serving local systems such as Coop and Migros." },
          { tag: "CITY", title: "Domestic urban facility clients", body: "Public transport, wayfinding, information screen and public-space projects across Beijing, Shanghai, Guangzhou, Shenzhen, Wuxi, Xi'an and Chongqing." },
        ],
      },
      projects: {
        eyebrow: "Catalog project update",
        title: "Representative projects from the latest catalog",
        sub: "The following summaries group catalog projects by region and product type; the Projects page can continue to expand the full case library.",
        items: [
          { tag: "Beijing", title: "Smart LED bus route signs", body: "High-brightness LED display, remote updates, energy-saving components and all-weather structure for clear route information day and night." },
          { tag: "Shanghai", title: "Smart bus shelter project", body: "High-strength steel, weather-resistant materials, modular installation, curved drainage canopy and integrated lighting for better waiting experiences." },
          { tag: "Guangzhou", title: "Huacheng Book House, Kapok kiosks and Nansha shelters", body: "Cultural design language with public service, information service, lighting, Wi-Fi, shared power banks and self-service vending." },
          { tag: "Shenzhen", title: "Qianhai and Futian smart shelters", body: "Wayfinding screens, touch interaction, evening lighting and open structures that turn bus stops into digital gateways." },
          { tag: "Wuxi / Xi'an / Chongqing", title: "Canal-city and LCD smart shelters", body: "Stainless structures, mirror-finish details, USB charging, vending integration and high-resolution information displays." },
          { tag: "Middle East", title: "Riyadh, Dammam, Mecca and Qatar projects", body: "Shade, ventilation, prefabricated units, overseas logistics and on-site support for high-heat environments and local architectural language." },
        ],
      },
      technology: {
        eyebrow: "Technology & manufacturing",
        title: "From metal fabrication to smart display systems",
        sub: "The latest catalog highlights HuaSheng's in-house capability for smart urban facilities and factory equipment.",
        items: [
          { tag: "DISPLAY", title: "In-house LED/LCD display systems", body: "Used in bus-shelter advertising screens, wayfinding screens and urban information kiosks, supporting real-time information, dynamic navigation and touch interaction." },
          { tag: "COATING", title: "Automatic powder coating line", body: "Automatic powder coating, manual touch-up, final assembly and quality checks for weather-resistant outdoor metal products." },
          { tag: "SMARTTECH", title: "Laser cutting and welding robots", body: "High-power laser cutting, welding robots, CNC shearing machines and aluminium profile cutters support precision manufacturing." },
          { tag: "ENERGY", title: "High-efficiency cooling system cooperation", body: "Cooling-system transformation for communication base stations using outdoor natural cooling sources and adaptive control algorithms." },
        ],
      },
      mission: {
        eyebrow: "Our mission",
        title: "Product quality is our future",
        body: "Product quality is HuaSheng's future. Through stable manufacturing, engineering delivery and long-term cooperation, we contribute to social development, industrial progress and industrial culture.",
      },
      values: {
        eyebrow: "Mission & values",
        title: "Insight · Precision · Advancement · Partnership",
        items: [
          { tag: "Insight", title: "Insight", body: "Understanding street furniture, public facilities and urban use cases so products fit real environments." },
          { tag: "Precision", title: "Precision", body: "Using engineering thinking, design coordination, equipment capability and quality processes to move projects faster and safer." },
          { tag: "Advancement", title: "Advancement", body: "More than three decades of manufacturing experience become continuous improvement and practical innovation at key project moments." },
          { tag: "Partnership", title: "Partnership", body: "Treating customer goals as shared missions and working with clients, designers, installers and suppliers to deliver together." },
        ],
      },
    },
    cap: {
      hero: {
        eyebrow: "Capabilities",
        title: "What a 50,000-m² metal workshop can actually do",
        sub: "Raw stock to packed container — every step closed inside our own plant.",
      },
      plantStats: [
        { num: "120,000", unit: "m²", label: "Total plant area" },
        { num: "5", unit: "", label: "Workshops" },
        { num: "297", unit: "", label: "Precision machines" },
        { num: "4", unit: "", label: "Production lines" },
        { num: "600+", unit: "", label: "Frontline staff" },
        { num: "40%", unit: "", label: "Spare capacity" },
      ],
      workshops: {
        title: "Five workshops",
        sub: "The plant is divided into an office building and five workshops, each owning one stage of the process.",
        items: [
          { tag: "01", title: "Hardware fabrication", body: "Laser cutting, CNC shearing and punching, bending, slotting, water jet. Forming cold-rolled steel, stainless, aluminium and galvanised plate." },
          { tag: "02", title: "Riveting & welding", body: "Robotic auto-welding paired with skilled manual welding. For both structural and visible parts." },
          { tag: "03", title: "Surface treatment", body: "Digital automatic spray line — pre-treatment, electrophoresis, powder coating, baking." },
          { tag: "04", title: "Clean assembly", body: "Final assembly, electrical and accessory integration, pre-shipment quality check in a clean environment." },
          { tag: "05", title: "Loading & dispatch", body: "Totem-style container loading to maximise utilisation, plus overseas installation guidance." },
        ],
      },
      equipment: {
        title: "Key equipment",
        sub: "297 machines covering every critical step from cutting to finishing.",
        items: ["400W laser cutter", "Robotic auto-welding cells", "Digital auto-spray line", "CNC bending / shearing", "CNC punching machines", "Tube bender / slotter", "Water jet cutter", "Electrophoresis pre-treatment line"],
      },
      process: {
        title: "Standard process",
        steps: [
          { n: "01", t: "Design & process review", d: "Engineering team reviews drawings and proposes process" },
          { n: "02", t: "IQC incoming inspection", d: "Steel, aluminium and accessories inspected before stocking" },
          { n: "03", t: "Cutting & forming", d: "Laser cutting, punching, bending, tube bending" },
          { n: "04", t: "Welding & riveting", d: "Robotic plus manual welding" },
          { n: "05", t: "Surface treatment", d: "Pre-treatment, electrophoresis, coating, baking" },
          { n: "06", t: "Assembly & commissioning", d: "Electrical, accessory and light box integration & test" },
          { n: "07", t: "FQC final inspection", d: "Full check of appearance, structure and electrical" },
          { n: "08", t: "Packing & shipping", d: "Totem loading, overseas installation guidance" },
        ],
      },
    },
    cases: {
      hero: {
        eyebrow: "Projects",
        title: "Three decades of metal we have made",
        sub: "From a stainless steel shelter at the Beijing Olympics to a government kiosk in a Nepalese hill town.",
      },
      filters: ["All", "Domestic shelters", "Overseas", "Steel structures", "OEM"],
      featured: {
        title: "Beijing Olympics stainless steel shelter",
        loc: "Beijing, China",
        amount: "Contract value RMB 12,723,000",
        year: "2008",
        body: "Stainless steel bus shelters around the Beijing Olympic venues — HuaSheng's flagship national contract.",
      },
      items: [
        { cat: "Domestic shelters", title: "Guangzhou's first modern shelter", loc: "Guangzhou, China", year: "1993", amount: "—", body: "The first generation of modern bus shelters for the city of Guangzhou — the opening chapter of modern shelter manufacturing in China." },
        { cat: "Domestic shelters", title: "Shanghai Expo bus shelters", loc: "Shanghai, China", year: "2010", amount: "RMB 25,645,000", body: "Bus shelters for the Shanghai Expo and downtown corridors, integrating cityscape design, light boxes and accessible waiting areas." },
        { cat: "Domestic shelters", title: "Hangzhou public bicycle stations", loc: "Hangzhou, China", year: "2012", amount: "RMB 7,963,000", body: "Stations for Hangzhou's public bicycle system, integrating information display and lighting." },
        { cat: "Domestic shelters", title: "Erdos shelter project", loc: "Erdos, China", year: "2015", amount: "RMB 3,000,000", body: "Shelters engineered for cold and arid climate — wind protection and heating built in." },
        { cat: "Overseas", title: "Doha bus shelters", loc: "Doha, Qatar", year: "2010s", amount: "—", body: "Shelters engineered for Middle Eastern heat — shading, cooling and integrated light boxes." },
        { cat: "Overseas", title: "Hong Kong MTR — ticket & enquiry counter", loc: "Hong Kong, China", year: "2016", amount: "—", body: "Stainless steel ticket and enquiry counters for Hong Kong MTR high-speed rail." },
        { cat: "Overseas", title: "Government of Nepal", loc: "Nepal", year: "2017", amount: "—", body: "Public facility programme — shelters, kiosks and information signage." },
        { cat: "Overseas", title: "New Zealand postal shelters", loc: "New Zealand", year: "2018", amount: "—", body: "Metal postal service shelters for an island climate." },
        { cat: "Overseas", title: "Oman public works", loc: "Oman", year: "2018", amount: "—", body: "Shelter and shading structures for a desert environment." },
        { cat: "Overseas", title: "Korea aluminium shelters", loc: "Korea", year: "2019", amount: "—", body: "All-aluminium modern bus shelters built to Korean municipal standards." },
        { cat: "Overseas", title: "Romania aluminium signage", loc: "Romania", year: "2017", amount: "—", body: "Aluminium wayfinding signs for the Romanian transport system." },
        { cat: "Overseas", title: "Riyadh bus shelters", loc: "Riyadh, Saudi Arabia", year: "2018", amount: "—", body: "Metal bus shelters for Middle Eastern heat, with a shading canopy, glass enclosure and standalone wayfinding pylon." },
        { cat: "Overseas", title: "Turkey & Turkmenistan", loc: "Turkey / Turkmenistan", year: "2019", amount: "—", body: "Municipal public facilities across Central and Western Asia." },
        { cat: "Steel structures", title: "Steel structure decoration", loc: "Multiple cities, China", year: "—", amount: "—", body: "Stainless steel facades, decorative structures and large-scale public space metalwork." },
        { cat: "OEM", title: "IKEA kitchen trolleys", loc: "—", year: "2001 – now", amount: "—", body: "Long-term OEM supplier of IKEA's metal kitchen trolley range." },
        { cat: "OEM", title: "IKEA kitchen cabinets & furniture", loc: "—", year: "2001 – now", amount: "—", body: "Metal parts for IKEA kitchen cabinets and furniture." },
        { cat: "OEM", title: "Towel racks & bathroom shelving", loc: "—", year: "2001 – now", amount: "—", body: "Volume OEM of bathroom metal accessories." },
        { cat: "OEM", title: "Shelving & metal parts", loc: "—", year: "2001 – now", amount: "—", body: "Home shelving and metal accessory OEM." },
      ],
    },
    quality: {
      hero: {
        eyebrow: "Quality & certification",
        title: "Trust, made into a verifiable process",
        sub: "ISO 9001 certified. Multiple design patents. DMAIC-based quality management.",
      },
      policy: {
        title: "Quality policy",
        sub: "As part of our ISO 9001 certification, our quality policy guides everything we do. Our commitment to quality stands on two pillars.",
        pillars: [
          { tag: "Pillar 1", t: "Keep our promises", d: "Deliver products that meet the agreed requirements, on time, satisfying customer needs and expectations." },
          { tag: "Pillar 2", t: "Continuously improve", d: "Monitor and continuously improve our business, products, services, organisation and people's performance." },
        ],
      },
      dmaic: {
        title: "DMAIC quality control",
        sub: "Customer experience → Define → Measure → Analyze → Improve → Control, applied from incoming material to outbound container.",
        steps: [
          { n: "D", t: "Define", d: "Lock the spec, customer expectations and acceptance criteria." },
          { n: "M", t: "Measure", d: "IQC, first-piece inspection, in-process data capture." },
          { n: "A", t: "Analyze", d: "Root-cause analysis on non-conforming items, CAR issued." },
          { n: "I", t: "Improve", d: "Process improvement and controlled rework to prevent recurrence." },
          { n: "C", t: "Control", d: "FQC final inspection, IPQC patrol, last verification before stock." },
        ],
      },
      certs: {
        title: "Certifications & patents",
        items: [
          { t: "ISO 9001 Quality Management", d: "Covers the full chain from design and fabrication to assembly and dispatch." },
          { t: "Bus shelter design patents", d: "Among the earliest holders of modern bus shelter design patents in China." },
          { t: "Structural utility patents", d: "Multiple utility patents covering structure, light boxes and connectors." },
          { t: "Approved IKEA supplier", d: "Long-term approved supplier under IKEA's global compliance audit." },
        ],
      },
    },
    contact: {
      hero: {
        eyebrow: "Contact",
        title: "Tell us about your project",
        sub: "City planning, advertising operations, overseas government procurement, or long-term OEM — we welcome a concrete conversation.",
      },
      info: {
        addr: { t: "Factory", v: "Guangzhou, Guangdong, China" },
        phone: { t: "Phone / WhatsApp", v: "+65 8309-9012" },
        email: { t: "Email", v: "hi@hua-sheng.org" },
        contact: { t: "Account contact", v: "Zayn Jarvis / Manager Liu" },
        hours: { t: "Working hours", v: "Daily 10:00-22:00 (GMT+8)" },
      },
      form: {
        title: "Project enquiry",
        sub: "Fill in this short form and we will reply within one business day.",
        fields: {
          name: "Your name",
          company: "Company / organisation",
          email: "Email *",
          phone: "Phone / WhatsApp",
          country: "Country / region",
          type: "Project type",
          types: ["Bus shelter project", "Advertising light box", "Steel structure", "OEM manufacturing", "Other"],
          message: "Briefly describe your needs (quantity, timing, budget…)",
          submit: "Send enquiry",
        },
      },
    },
  },
};
